config/routes.rb
Rails.application.routes.draw do

  # Volunteer routes
  devise_for :volunteers, :path => 'volunteer', :controllers => {:registrations => "registrations"}
  resources :volunteers, :only => [:index] do
    member do
      patch 'approve'
      patch 'ban'
      patch 'make_admin'
    end
  end
  get '/volunteers/home', to: 'volunteers#home', as: 'volunteers_home'

  # Organization routes
  resources :organizations, only: [:index, :new, :create, :destroy]

  # Voter routes
  resources :voters, only: [:index, :new, :create] do
    member do
      get 'cancel'
      get 'activate'
    end
  end
  get '/voters/:hashed_id', to: 'voters#voter_home', as: 'voter_home'

  # Match routes
  resources :matches, only: [:index, :create, :show] do
    member do
      # Volunteer match routes
      post 'message'
      get 'decline'
      post 'complete'
      # Voter match routes
      get 'voter_accept'
      get 'voter_reject'
      post 'voter_request_time'
    end
  end

  # Document routes
  resources :documents, :path => 'voter-resources', only: [:index, :show, :new, :create, :update, :destroy]

  # Metrics routes
  resources :metrics, only: [:index]

  # Translation routes
  resources :locales do
    resources :translations, constraints: { :id => /[^\/]+/ }
  end

  # Application routes
  get '/', to: 'application#index', as: 'homepage'
  get '/feedback', to: 'application#feedback', as: 'feedback'
  post '/submit_feedback', to: 'application#submit_feedback', as: 'submit_feedback'
  get '/absentee-registration', to: 'application#absentee_registration', as: 'absentee_registration'
  get '/about', to: 'application#about', as: 'about'
  get '/guidelines', to: 'application#community_guidelines', as: 'community_guidelines'
  get '/privacy', to: 'application#privacy_policy', as: 'privacy_policy'
  get '/terms', to: 'application#terms_of_service', as: 'terms_of_service'

  root :to => 'application#index'
  
end

app/models/translation.rb
class Translation < ActiveRecord::Base
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
	before_action :authenticate_admin!
	before_action :find_locale
	before_action :retrieve_key, only: [:create, :update]
	before_action :find_translation, only: [:edit, :update]

	def index
		@translations = Translation.locale(@locale)
	end

	def new
		@translation = Translation.new(locale: @locale, key: params[:key])
	end

	def create
		@translation = Translation.new(translation_params)
		if @translation.value == default_translation_value
			flash[:alert] = "Your new translation is the same as the default."
			render :new
		else
			if @translation.save
				flash[:success] = "Translation for #{ @key } updated."
				I18n.backend.reload!
				redirect_to locale_translations_url(@locale)
			else
				render :new
			end
		end
	end

	def edit
	end

	def update
		if @translation.update(translation_params)
			flash[:notice] = "Translation for #{ @key } updated."
			I18n.backend.reload!
			redirect_to locale_translations_url(@locale)
		else
			render :edit
		end
	end

	def destroy
		Translation.destroy(params[:id])
		I18n.backend.reload!
		redirect_to locale_translations_url(@locale)
	end

	private

	def find_locale
		@locale = params[:locale_id]
	end

	def find_translation
		@translation = Translation.find(params[:id])
	end

	def retrieve_key
		@key = params[:i18n_backend_active_record_translation][:key]
	end

	def translation_params
		params.require(:i18n_backend_active_record_translation).permit(:locale,
			:key, :value)
	end

	def default_translation_value
		I18n.t(@translation.key, locale: @locale)
	end
end

app/helpers/translations_helper.rb
module TranslationsHelper
	def flatten_hash hash
		hash.each_with_object({}) do |(k, v), h|
			if v.is_a? Hash
				flatten_hash(v).map do |h_k, h_v|
					h["#{k}.#{h_k}"] = h_v
				end
			else 
				h[k] = v
			end
		 end
	end

	def translation_keys
		flatten_hash(YAML.load_file('config/locales/en.yml')["en"]).keys
	end

	def translation_for_key(translations, key)
		hits = translations.to_a.select{ |t| t.key == key }
		hits.first
	end
end

app/views/translations/edit.html.erb
<main class="page <%= t('direction') %>">

	<div class="wrapper <%= t('direction', locale: @locale) %>">
		<%= form_for @translation, url: locale_translation_path do |form| %>
		  <%= form.label :locale %> <%= form.text_field :locale, readonly: true %>
		  <%= form.label :key %> <%= form.text_field :key, readonly: true %>
		  <%= form.label :value %> <%= form.text_area :value %>

		  <%= form.submit 'Save Translation', class: "button" %> <%= link_to "Cancel", locale_translations_url(@locale), class: "btn-outline button" %>
		<% end %>
	</div>
	
</main>

app/views/translations/index.html.erb
<main class="table translations">

  <div class="wrapper">

    <h1>Translations for <%= t('locale_name', locale: @locale) %></h1>

    <% if translation_for_key(@translations, 'enabled').present? %>
      <% enabled = translation_for_key(@translations, 'enabled') %>
      <% form_url = locale_translation_path(:id => enabled.id) %>
    <% else %>
      <% enabled = Translation.new(locale: @locale, key: 'enabled', value: 'false') %>
      <% form_url = locale_translations_path %>
    <% end %>
    <%= form_for enabled, url: form_url do |form| %>
      <span>Translation State: <%= enabled.value == 'false' ? 'Disabled' : 'Enabled' %></span>
      <%= form.hidden_field :locale %>
      <%= form.hidden_field :key %>
      <%= form.hidden_field :value, { :value => enabled.value == 'false' ? 'true' : 'false' } %>
      <%= form.submit enabled.value == 'false' ? 'Enable' : 'Disable', class: "button" %>
    <% end %>

    <table>
      <thead>
        <tr>
          <th class="row-id">Translation Key</th>
          <th class="row-en">English Version</th>
          <th class="row-trans"><%= t('locale_name', locale: @locale) %> Translation</th>
          <th class="row-action">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% translation_keys.each do |key| %>
          <% next if key == 'enabled' %>
          <% translation = translation_for_key(@translations, key) %>
          <tr id="<%= key %>">
            <td><%= key %></td>
            <td><%= t(key, locale: 'en') %></td>
            <td class="<%= t('direction', locale: @locale) %>"><%= translation.nil? ? I18n.t(key, locale: @locale) : translation.value %></td>
            <td>
              <% if translation.nil? %>
                <%= link_to "Edit", new_locale_translation_url(@locale, key: key), class: "button" %>
              <% else %>
                <%= link_to "Edit", edit_locale_translation_url(@locale, translation), class: "button" %>
                <%= link_to "Reset", locale_translation_url(@locale, translation), method: :delete, class: "button btn-outline", data: { confirm: "Are you sure?" } %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div><!--.wrapper-->

</main><!--.table-->

app/views/translations/new.html.erb
<main class="page">

	<div class="wrapper <%= t('direction', locale: @locale) %>">
		<%= form_for @translation, url: locale_translations_path do |form| %>
		  <%= form.label :locale %> <%= form.text_field :locale, readonly: true %>
		  <%= form.label :key %> <%= form.text_field :key, readonly: true %>
		  <%= form.label :value %> <%= form.text_area :value, value: I18n.t(@translation.key, locale: @locale) %>

		  <%= form.submit 'Save Translation', class: "button" %> <%= link_to "Cancel", locale_translations_url(@locale), class: "btn-outline button" %>
		<% end %>
	</div><!--.wrapper-->
	
</main>