config/routes.rb
Rails.application.routes.draw do

  # Volunteer routes
  devise_for :volunteers, :path => 'volunteer', :controllers => {:registrations => "registrations"}
  resources :volunteers, :only => [:index] do
    member do
      patch 'approve'
      patch 'ban'
      patch 'make_admin'
    end
  end
  get '/volunteers/home', to: 'volunteers#home', as: 'volunteers_home'

  # Organization routes
  resources :organizations, only: [:index, :new, :create, :destroy]

  # Voter routes
  resources :voters, only: [:index, :new, :create] do
    member do
      get 'cancel'
      get 'activate'
    end
  end
  get '/voters/:hashed_id', to: 'voters#voter_home', as: 'voter_home'

  # Match routes
  resources :matches, only: [:index, :create, :show] do
    member do
      # Volunteer match routes
      post 'message'
      get 'decline'
      post 'complete'
      # Voter match routes
      get 'voter_accept'
      get 'voter_reject'
      post 'voter_request_time'
    end
  end

  # Document routes
  resources :documents, :path => 'voter-resources', only: [:index, :show, :new, :create, :update, :destroy]

  # Metrics routes
  resources :metrics, only: [:index]

  # Translation routes
  resources :locales do
    resources :translations, constraints: { :id => /[^\/]+/ }
  end

  # Application routes
  get '/', to: 'application#index', as: 'homepage'
  get '/feedback', to: 'application#feedback', as: 'feedback'
  post '/submit_feedback', to: 'application#submit_feedback', as: 'submit_feedback'
  get '/absentee-registration', to: 'application#absentee_registration', as: 'absentee_registration'
  get '/about', to: 'application#about', as: 'about'
  get '/guidelines', to: 'application#community_guidelines', as: 'community_guidelines'
  get '/privacy', to: 'application#privacy_policy', as: 'privacy_policy'
  get '/terms', to: 'application#terms_of_service', as: 'terms_of_service'

  root :to => 'application#index'
  
end

app/views/shared/_footer.html.erb
<footer class="mobile-only">

	<div class="wrapper">

		<div class="mobile-only">
			<a href="<%= feedback_path %>"><%= t('voter_dashboard.menu.feedback')%></a>
		</div><!--.mobile-only-->
		
		<div class="share-with-community">

			<div><%= t('voter_dashboard.menu.share')%></div>

			<div class="buttons">
				<a href=""><i class="fa fa-facebook" aria-hidden="true"></i></a>
				<a href=""><i class="fa fa-twitter" aria-hidden="true"></i></a>
				<a href="" class=""><i class="fa fa-envelope" aria-hidden="true"></i></a>
				<div class="clear-fix"></div>
			</div>

		</div><!--.share-with-community-->

		<div class="terms">
			<ul>
				<li><a href="<%= homepage_path %>">&copy; VoterVOX</a></li>
				<li><a href="<%= community_guidelines_path %>">Community Guidelines</a></li>
				<li><a href="<%= privacy_policy_path %>">Privacy Policy</a></li>
				<li><a href="<%= terms_of_service_path%>">Terms</a></li>
			</ul>
			<div class="clear-fix"></div>
		</div><!--.terms-->

	</div><!--.wrapper-->

</footer><!--.mobile-only-->

app/views/shared/_share_with_community.html.erb
<div class="share-with-community">

	<div class="share-title">Share with Your Community</div>
	
	<div class="buttons">
		<a class="popup-link" href="https://www.facebook.com/sharer/sharer.php?u=http://beta.votervox.org"><i class="fa fa-facebook" aria-hidden="true"></i></a>
		<a class="popup-link" href="https://twitter.com/intent/tweet?text=VoterVOX"><i class="fa fa-twitter" aria-hidden="true"></i></a>
		<a class="popup-link" href="mailto:?subject=VoterVOX&amp;body=www.votervox.org"><i class="fa fa-envelope" aria-hidden="true"></i></a>
		<div class="clear-fix"></div>
	</div>

</div><!--.share-with-community-->
<div class="terms">
	<ul>
		<li><a href="<%= about_path %>">About VoterVOX</a></li>
		<li><a href="<%= community_guidelines_path %>">Community Guidelines</a></li>
		<li><a href="<%= homepage_path %>">&copy; VoterVOX</a></li>
		<li><a href="<%= privacy_policy_path %>">Privacy Policy</a></li>
		<li><a href="<%= terms_of_service_path %>">Terms</a></li>
		<div class="clear-fix"></div>
	</ul>
	<div class="clear-fix"></div>
</div>

app/views/shared/_volunteer_sidebar.html.erb
<aside class="tablet desktop">

	<a class="brand" href="<%= homepage_path %>">VoterVox</a>
	
	<div class="volunteer-dashboard">

		<% if admin_signed_in? %>
		<div class="green">Admin Dashboard</div>
		<% else %>
		<div class="green">Volunteer Dashboard</div>		
		<% end %>

	</div><!--.volunteer-dashboard-->

	<% if admin_signed_in? %>
		<a class="button <%= at_voters_list? ? "selected" : "pink" %>" href="<%= voters_path %>">
			Voters
		</a>
		<a class="button <%= at_volunteer_list? ? "selected" : "pink" %>" href="<%= volunteers_path %>">Volunteers</a>
		<a href="<%= organizations_path %>" class="button <%= at_organization_home? ? "selected" : "pink" %>">Organizations</a>
		<a href="<%= metrics_path %>" class="button <%= at_metrics? ? "selected" : "pink" %>">Metrics</a>
	<% else %>
		<a href="<%= volunteers_home_path %>" class="button <%= at_volunteer_home? ? "selected" : "pink" %>">Getting Started</a>		
	<% end %>

	<% if approved_volunteer_signed_in? %>
		<a href="<%= matches_path %>" class="button <%= at_matches? ? "selected" : "pink" %>">Your Matches</a>
	<% end %>

	<a href="<%= documents_path %>" class="button <%= at_documents_index? ? "selected" : "pink" %>" >Voter Resources</a>

	<a href="<%= new_document_path %>" class="button add-menu <%= at_documents_new? ? "selected" : "pink" %>">Add a Translated Resource</a>

	<% if !admin_signed_in? %>

		<a class="button <%= at_feedback? ? "selected" : "pink" %>"  href="<%= feedback_path %>">
			Give Feedback
		</a>

	<% end %>
		<%= link_to('Logout', destroy_volunteer_session_path, :method => :delete, class: "button logout") %>

	<%= render "/shared/share_with_community" %>

</aside><!--.tablet-desktop-->

app/views/shared/_voter_sidebar.html.erb
<aside class="tablet desktop">

	<a class="brand" href="<%= homepage_path %>">VoterVox</a>

	<div class="voter-dashboard">
		<div class="green"><%= t( 'voter_dashboard.menu.dashboard') %></div>
	</div><!--.voter-dashboard-->
	
	<% if @voter.present? %>

	<div class="voter-menu">
		<a href="<%= @voter.home_url%>" class="button <%= at_voter_home? ? "selected" : "pink" %>" ><%= t('voter_dashboard.menu.translator') %></a>

		<% else %>

		<a href="<%= new_voter_path %>" class="button pink" ><%= t('voter_registration.title') %></a>

		<% end %>

		<a href="<%= documents_path %>" class="button <%= at_documents_index? ? "selected" : "pink" %>"><%= t('voter_dashboard.menu.resources')%></a>
		<a href=<%= absentee_registration_path %> class="button <%= at_absentee_ballot? ? "selected" : "pink" %>">Absentee Registration</a>

		<a class="button <%= at_feedback? ? "selected" : "pink" %>"  href="<%= feedback_path %>">
			<%= t('voter_dashboard.menu.feedback')%>
		</a>
	</div>

	<%= render "/shared/share_with_community" %>

</aside><!--.tablet.desktop-->