config/routes.rb
Rails.application.routes.draw do

  # Volunteer routes
  devise_for :volunteers, :path => 'volunteer', :controllers => {:registrations => "registrations"}
  resources :volunteers, :only => [:index] do
    member do
      patch 'approve'
      patch 'ban'
      patch 'make_admin'
    end
  end
  get '/volunteers/home', to: 'volunteers#home', as: 'volunteers_home'

  # Organization routes
  resources :organizations, only: [:index, :new, :create, :destroy]

  # Voter routes
  resources :voters, only: [:index, :new, :create] do
    member do
      get 'cancel'
      get 'activate'
    end
  end
  get '/voters/:hashed_id', to: 'voters#voter_home', as: 'voter_home'

  # Match routes
  resources :matches, only: [:index, :create, :show] do
    member do
      # Volunteer match routes
      post 'message'
      get 'decline'
      post 'complete'
      # Voter match routes
      get 'voter_accept'
      get 'voter_reject'
      post 'voter_request_time'
    end
  end

  # Document routes
  resources :documents, :path => 'voter-resources', only: [:index, :show, :new, :create, :update, :destroy]

  # Metrics routes
  resources :metrics, only: [:index]

  # Translation routes
  resources :locales do
    resources :translations, constraints: { :id => /[^\/]+/ }
  end

  # Application routes
  get '/', to: 'application#index', as: 'homepage'
  get '/feedback', to: 'application#feedback', as: 'feedback'
  post '/submit_feedback', to: 'application#submit_feedback', as: 'submit_feedback'
  get '/absentee-registration', to: 'application#absentee_registration', as: 'absentee_registration'
  get '/about', to: 'application#about', as: 'about'
  get '/guidelines', to: 'application#community_guidelines', as: 'community_guidelines'
  get '/privacy', to: 'application#privacy_policy', as: 'privacy_policy'
  get '/terms', to: 'application#terms_of_service', as: 'terms_of_service'

  root :to => 'application#index'
  
end

app/models/voter.rb
class Voter < ActiveRecord::Base
	scope :active, -> { where("active = true") }
	scope :inactive, -> { where("active = false") }

	has_many :matches

	COMMUNICATION_MODES = ['Text Message','Email']
	COMFORT_LEVEL = ['1','2','3','4','5']

	before_validation :format_phone

	def format_phone
		return unless sms_contact?
		phone_regex = /\A\(?(\d{3})\)?[\s.-]?(\d{3})[\s.-]?(\d{4})\z/
		re_match = self.contact.match(phone_regex)
		return if re_match.nil?
		self.contact = re_match[1] + re_match[2] + re_match[3]
	end

	validates :firstname, length: { in: 1..128 }
	validates :lastname, length: { in: 1..128 }
	validates :communication_mode, inclusion: { in: COMMUNICATION_MODES }
	validates :contact, uniqueness: { scope: :communication_mode,
		message: "has been used already. Please visit the homepage link send to you to access your match information." }
	validates :contact, format: { with: /\A\d{10}\z/,
		message: "must be a valid phone number" }, if: :sms_contact?
	validates :contact, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/,
		message: "must be a valid email address" }, if: :email_contact?
	validates :address, length: { in: 5..255 }
	validates :languages, presence: true
	validates :english_comfort, presence: true

	# Accessor functions
	def hashed_id
		(((0x0000FFFF & id)<<16) + ((0xFFFF0000 & id)>>16)).to_s(36)
	end
	def home_url
		['/voters/', hashed_id].join('')
	end
	def active_match
		self.matches.active.first
	end
	def declined_match
		self.matches.voter_declined.first
	end
	def completed_match
		self.matches.completed.last
	end

	# Volunteer Match Functions
	def volunteer_distance volunteer
		Geocoder::Calculations.distance_between [self.latitude, self.longitude], [volunteer.latitude, volunteer.longitude] rescue nil
	end

	# Helper functions
	def active?
		active
	end
	def sms_contact?
		communication_mode == 'Text Message'
	end
	def email_contact?
		communication_mode == 'Email'
	end
	def self.communication_options
		COMMUNICATION_MODES.zip(COMMUNICATION_MODES)
	end
	def self.comfort_options
		COMFORT_LEVEL.zip(COMFORT_LEVEL)
	end
	def self.find_by_hashed_id hashed_id
		voter_id = hashed_id.to_i(36)
		Voter.find( ((0x0000FFFF & voter_id)<<16) + ((0xFFFF0000 & voter_id)>>16) ) rescue nil
	end
	def self.matched
		Voter.includes(:matches).active.select{ |v| v.matches.active.present? }
	end
	def self.unmatched
		Voter.includes(:matches).active.select{ |v| v.matches.active.empty? }
	end
	def self.completed
		Voter.includes(:matches).inactive.select{ |v| v.matches.completed.present? }
	end
end

app/controllers/voters_controller.rb
class VotersController < ApplicationController
	before_action :authenticate_admin!, only: [:index]
	before_action :authenticate_voter!, only: [:voter_home, :cancel, :activate]
	layout :determine_layout

	def index
		@voters = Voter.all
		@unmatched = Voter.unmatched
		@matched = Voter.matched
		@completed = Voter.completed
	end

	def new
		@voter = Voter.new
		@communication_options = Voter.communication_options
		@comfort_options = Voter.comfort_options
		@client = GooglePlaces::Client.new('AIzaSyAB2Ap-u99P3gRwZFqz3HuonM5_v4v18do')
	end

	def create
		@voter = Voter.new(voter_params)

		if @voter.save
			# Notify voter
			sms_message = [t('voter_dashboard.request.message.sms'), full_url(@voter.home_url)].join(' ')
			VoterVoxSms.new.send @voter.contact, sms_message if @voter.sms_contact?
			VoterNotifier.signup_confirmation(@voter).deliver_now if @voter.email_contact?

			# Save record to ActionNetwork if voter has email
			if @voter.email_contact?
				voter_data = {
					:firstname => @voter.firstname,
					:lastname => @voter.lastname,
					:email => @voter.contact,
					:zip => @voter.zip
				}
				ActionNetwork.new.submit_form ENV['ACTIONNETWORK_VOTER_FORM'], voter_data
			end

			redirect_to @voter.home_url
		else
			@communication_options = Voter.communication_options
			@comfort_options = Voter.comfort_options
			render 'new'
		end
	end

	def voter_home
		@match = @voter.active_match || @voter.declined_match
		@completed = @voter.completed_match

		if @match.present?
			@proposal = @match.interactions.proposals.first
			@reschedule = @match.interactions.reschedules.first
			@volunteer = @match.volunteer
			render 'voter_match'
		elsif @voter.active?
			render 'voter_welcome'
		elsif @completed.present?
			@user_type = 'Voter'
			render 'voter_completed'
		else
			render 'voter_cancelled'
		end
	end

	def cancel
		@voter.update(:active => false)
		@voter.matches.active.each do |match|
			VoterVoxSms.new.send match.volunteer.phone, [match.voter.firstname, t('volunteer_sms.match_rejected'), full_url(matches_path)].join(' ')
			match.voter_decline!
			match.save
		end

		redirect_to @voter.home_url
	end

	def activate
		@voter.update(:active => true)

		redirect_to @voter.home_url
	end

	private

	def voter_params
		params.require(:voter).permit(:firstname, :lastname, :communication_mode, :contact, :locale,
			:address, :city, :state, :zip, :latitude, :longitude, {:languages => []}, :english_comfort, :first_time_voter)
	end

	def determine_layout
		return "volunteer" if action_name == "index"
		return "application" if action_name == "new" || action_name == "create"
		return "voter"
	end

end

app/helpers/voters_helper.rb
module VotersHelper

end

app/views/voters/index.html.erb
<main class="dashboard">
	<div class="wrapper">
		<section class="match-results">
			<div class="wrapper">
				<h1>VoterVOX Voters</h1>
				<ul class="status">
					<li><a class="voters-toggle current" href="#" data-voters="unmatched">Unmatched Voters</a></li>
					<li><a class="voters-toggle" data-voters="matched" href="#">Matched Voters</a></li>
					<li><a class="voters-toggle" href="#" data-voters="completed">Completed Matches - Voters Helped</a></li>
					<div class="clear-fix"></div>
				</ul>
				<div class="divi-bar"></div>

				<div id="unmatched" class="voter-boxes">

					<% @unmatched.each do |voter| %>

					<div class="voter-box">
						<div class="voter-info">
							<h2><%= voter.firstname %> <%= voter.lastname %></h2>
							<hr/>
							<ul>
								<li><strong>Email/Phone:</strong> <%= voter.contact %></li>
								<% first_time_voter = voter.first_time_voter %>
								<li><strong>First Time Voter: </strong><%= first_time_voter ? 'yes' : 'no'%></li><li><strong>City:</strong> <%= voter.city %></li>
								<li><strong>Languages:</strong> <%= voter.languages.join(', ') %></li>
								<li><strong>English Proficiency:</strong> <%= voter.english_comfort %> </li>
							</ul>
						</div><!--.voter-info-->
						
					</div><!--.voter-box-->

					<% end %>
					<% if @unmatched.length == 0 %>

						<div class="voter-box">
							<h2  class="no-matches">No Unmatched Voters</h2>
						</div>

					<% end %>
				</div><!--#unmatched.voter-boxes-->

				

				<div id="matched" class="hide voter-boxes">
					<% @matched.each do |voter| %>

					<div class="voter-box">
						<div class="voter-info">
							<h2><%= voter.firstname %> <%= voter.lastname %></h2>
							<hr/>
							<ul>
								<li><strong>Email/Phone:</strong> <%= voter.contact %></li>
								<% first_time_voter = voter.first_time_voter %>
								<li><strong>First Time Voter: </strong><%= first_time_voter ? 'yes' : 'no'%></li>
								<li><strong>City:</strong> <%= voter.city %></li>
								<li><strong>Languages:</strong> <%= voter.languages.join(', ') %></li>
								<li><strong>English Proficiency:</strong> <%= voter.english_comfort %> </li>

							</ul>
						</div><!--.voter-info-->
						
					</div><!--.voter-box-->

					<% end %>
					<% if @matched.length == 0 %>

					<div class="voter-box">
						<h2 class="no-matches">No Matched Voters</h2>
					</div><!--.matched-->

					<% end %>
				</div><!--#matched.voter-boxes-->


				

				<div id="completed" class="hide voter-boxes">
					<% @completed.each do |voter| %>

					<div class="voter-box">
						<div class="voter-info">
							<h2><%= voter.firstname %> <%= voter.lastname %></h2>
							<hr/>
							<ul>
								<li><strong>Email/Phone:</strong> <%= voter.contact %></li>
								<li><strong>First Time Voter: </strong><%= voter.first_time_voter %></li>
								<li><strong>City:</strong> <%= voter.city %></li>
								<li><strong>Languages:</strong> <%= voter.languages.join(', ') %></li>
								<li><strong>English Proficiency:</strong> <%= voter.english_comfort %> </li>
								<% first_time_voter = voter.first_time_voter %>
								<% if first_time_voter %>
									<li><strong>First Time Voter</strong></li>
								<% end %>
							</ul>
						</div><!--.voter-info-->
						
					</div><!--.voter-box-->

					<% end %>
					<% if @completed.length == 0 %>

						<div class="voter-box">
							<h2 class="no-matches">No Completed Matches</h2>
						</div>

					<% end %>

				</div><!--#completed.voter-boxes-->

				

			</div><!--.wrapper-->

		</section><!--.match-results-->

	</div><!--.wrapper-->
</main>

app/views/voters/new.html.erb
<main class="sign-up">
	<div class="wrapper">

		<h1><%= t('voter_registration.title') %></h1>
		<div class="pink-line"></div>
		<%= form_for :voter, url: voters_path, method: 'POST' do |f| %>
            <%= f.hidden_field :locale, :value => params[:locale] || 'en' %>

			<% if @voter.errors.any? %>
		        <% @voter.errors.full_messages.each do |msg| %>
		        	<p class='error'><%= msg %></p>
		        <% end %>
			<% end %>

			<div class="float-left first-name">
				<%= f.label :"#{t('voter_registration.form.firstname')}*", {:for => "voter_firstname"} %>
				<%= f.text_field :firstname, { :placeholder => "#{t('voter_registration.form.firstname')}", :class => 'first-name' } %>
			</div>

			<div class="float-left">
				<%= f.label :"#{t('voter_registration.form.lastname')}*", {:for => "voter_lastname"} %>
				<%= f.text_field :lastname, { :placeholder => "#{t('voter_registration.form.lastname')}", :class => 'last-name' } %>
			</div>

			<%= f.label :"#{t('voter_registration.form.communication_type')}*", {:for => "voter_communication_mode"} %>
			<%= f.select :communication_mode,
				options_for_select(@communication_options, @voter.communication_mode || false),
				{ include_blank: "#{t('voter_registration.form.communication_type')}" } %>

			<%= f.label :"#{t('voter_registration.form.contact')}*", {:for => "voter_contact"} %>
			<%= f.text_field :contact, { :placeholder => "#{t('voter_registration.form.contact_placeholder')}" } %>

			<%= f.label :"#{t('voter_registration.form.address')}*", {:for => "address"} %>
			<%= f.text_field :address, { :placeholder => 'Enter your address', :required => true, :id => "autocomplete" } %>
            <%= f.hidden_field :latitude, { :id => "latitude", :class => "field" } %>
            <%= f.hidden_field :longitude, { :id => "longitude", :class => "field" } %>
            <%= f.hidden_field :city, { :id => "locality", :class => "field" } %>
            <%= f.hidden_field :state, { :id => "administrative_area_level_1", :class => "field" } %>
            <%= f.hidden_field :zip, { :id => "postal_code", :class => "field" } %>
            <input class="field" id="street_number" disabled="true" type="hidden"></input>
            <input class="field" id="route" disabled="true" type="hidden"></input>
            <input class="field" id="country" name="country" disabled="true" type="hidden"></input>


			<%= field_set_tag "#{t('voter_registration.form.languages')}*", class: 'languages' do %>
			<% language_list.each do |language| %>
				<%= label_tag 'language_'+slugify(language), language do %> 
				  <%= check_box_tag 'voter[languages][]', language, chosen_language(@voter, language), id: 'language_'+slugify(language) %>
				  <%=language%>
				<% end %>
			  	
			  <% end %>
			  	<div class="clear-fix"></div>
			<% end %>


			<%= f.label :"#{t('voter_registration.form.english_comfort')}*", {:for => "english_comfort"}  %>
			<%= f.select :english_comfort,
				options_for_select(@comfort_options, @voter.english_comfort || false),
				{ include_blank: 'Select One' } %>

			<%= f.label :"#{t('voter_registration.form.first_time_voter')}*", {:for => "english_comfort"}, {:for => "first_time_voter" } do %>
				<%= f.check_box :first_time_voter %><%= t('voter_registration.form.first_time_voter') %>
			<% end %>
			<%= f.submit "#{t('voter_registration.button')}", :class => 'big-button button' %>
			<div class="opt-in-language">
				<%= t('voter_registration.disclaimer') %>
			</div><!--.opt-in-language-->

		<% end %>
	</div><!--.wrapper-->
</main>

app/views/voters/voter_cancelled.html.erb
<main class="dashboard">
	<section class="message">

		<h1><%= t('voter_dashboard.cancel_lightbox.title')%></h1>

	</section><!--.message-->
	
	<section class="translator-selection">
	
		<h2 class="cancel-title"><%= t('voter_dashboard.cancel_lightbox.activate_title')%></h2>
		<%= link_to t('voter_dashboard.cancel_lightbox.button'), activate_voter_path(@voter), class: "btn-outline" %>

	</section><!--.next-steps-->

</main>

app/views/voters/voter_completed.html.erb
<main class="dashboard">

	<section class="message completed-title section-title">
	
		<h1><%= t('voter_dashboard.completed.title') %></h1>
		<p><%= t('voter_dashboard.completed.prompt')%></p>
		<%= link_to t('voter_dashboard.completed.button'), activate_voter_path(@voter), class: "btn-outline" %>
		<div class="clear-fix"></div>
	</section><!--.message-->
	
	<section class="feedback">

		<p><%= t('voter_dashboard.completed.feedback_prompt')%></p>
		<%= form_tag submit_feedback_path, method: 'POST' do %>
			<%= hidden_field_tag 'subject', 'Feedback from ' + @user_type.upcase %>
			<%= hidden_field_tag 'firstname', @voter.firstname %>
			<%= hidden_field_tag 'lastname', @voter.lastname %>
			<%= hidden_field_tag 'contact', @voter.contact %>

			<%= field_set_tag 'Your feedback to VoterVOX *' do %>
				<%= text_area_tag 'message', '', { :placeholder => 'Your feedback to VoterVOX' } %>
			<% end %>

			<%= submit_tag t('voter_dashboard.completed.feedback_button'), class: "button" %>

		<% end %>
		
	</section><!--.next-steps-->

</main>

app/views/voters/voter_home.html.erb
<main class="dashboard">
	<div class="wrapper">
		<div class="notice"><%= notice %></div>
		<div class="alert"><%= alert %></div>

		<section class="message">
			<div class="wrapper">
				<h1><%= @voter.firstname %>, your translator request has been submitted</h1>
			</div>
		</section><!--.message-->
		<section class="next-steps">
			<div class="wrapper">
				<h2>Your Next Steps</h2>
				<ul>
					<li><strong>Step 1:</strong> You will be contacted once a translator matches up.</li>
					<li><strong>Step 2:</strong> Set a date, time and location with your translator.</li>
					<li><strong>Step 3:</strong> Meet in person and get your voting questions answered.</li>
					<li><strong>Step 4:</strong> Vote!</li>
				</ul>
			</div>
		</section><!--.next-steps-->

		<section class="more-info">
			<div class="wrapper">

				<p>To view your profile, save and use this link:</p>
				<input type="text" value="www.votervox.org/profile=?buakaw">
				<p>(You will also find this link in your confirmation email).</p>
			</div><!--.wrapper-->

		</section><!--.more-info-->
		<section class="cancel-request">
			<div class="wrapper">
				<button class="button btn-outline">Cancel Your Request</button>
				<div class="clear-fix"></div>
			</div>
			
		</section>

		<section class="voter-resources">
			<div class="wrapper">
				<h2>Feel free to check out our Voter Resources in the mean time.</h2>
				<a href="/documents" class="button">Voter Resources</a>
			</div>
			
		</section>
	</div>
</main>

app/views/voters/voter_match.html.erb
<main class="dashboard">

	<section class="message section-title">

		<div class="wrapper">

			<h1><%= t('voter_dashboard.matched.title')%></h1>

			<p><%= t('voter_dashboard.matched.subtitle')%></p>
			<div class="divi-bar"></div>

		</div><!--.wrapper-->

	</section><!--.message-->

	<div class="wrapper">

		<section class="translator">

			<div class="translator-image"><img src="<%= @volunteer.profile_image.present? ? @volunteer.profile_image.url(:square) : asset_path('volunteer.png') %>">
			</div>
			<div class="details">
				<h2><%= @volunteer.firstname %> <%= @volunteer.lastname %></h2>
				<hr />
				<ul>
				<% distance = @voter.volunteer_distance(@volunteer) %>
					<li><strong><%= t('voter_dashboard.matched.volunteer.city')%>:</strong> <%= @volunteer.city %></li>

					<% unless distance.nil? || distance.nan? %>
					<li><strong><%= t('voter_dashboard.matched.volunteer.proximity')%>:</strong> <%= distance %></li>
					<% end %>

					<li><strong><%= t('voter_dashboard.matched.volunteer.languages')%>:</strong> <%= @volunteer.languages.join(', ') %></li>
				</ul>
			</div><!--.details-->

			<div class="clear-fix"></div>

		</section><!--.translator-->

	<% if @proposal.present? %>

		<section class="available-times">

			<div class="wrapper">

				<h2><%= @volunteer.firstname %>'s <%= t('voter_dashboard.matched.contact')%>:</h2>
				<textarea readonly><%= @proposal.message %></textarea>
				
				<% if @match.proposed? %>

					<%= link_to t('voter_dashboard.matched.accept_button'), @match.voter_accept_url, class: "button accept" %>
					<%= link_to t('voter_dashboard.matched.decline_button'), @match.voter_reject_url, class: "button decline",
						data: { confirm: "Are you sure you'd like to decline this match?" } %>
					<div class="clear-fix"></div>
					<a class="request button lightbox-button" data-lightbox="request_time"><%= t('voter_dashboard.matched.reschedule_button')%></a>
				<% end %>
				
			</div><!--.wrapper-->

		</section><!--.available-times-->

	<% end %>

	</div><!--.wrapper-->

</main>

<% if @match.status == MatchesHelper::STATUS_ACCEPTED %>

	<div id="fade" class="green-overlay"></div><!--.green_overlay-->
	<div id="accepted_message" class="light lightbox">
		<div class="close-icon"></div>
		<h2><%= t('voter_dashboard.accepted.title1') %> <%= @volunteer.firstname%> <%= t('voter_dashboard.accepted.title2') %>.</h2>
		<div class="pink-hr"></div>
		<div>
			<p><%= t('voter_dashboard.accepted.prompt1') %></p>
			<p><%= @volunteer.firstname%> <%= t('voter_dashboard.accepted.prompt2') %>.</p>
		</div><!--.next-step-->
		<div class="contact-info pink-box">
			<p><%= @volunteer.firstname%>'s <%= t('voter_dashboard.accepted.contact')%>:</p>
			<div class="phone-number"><%= @volunteer.phone %></div>
		</div><!--.contact-info-->

	</div><!--.light#accepted_message-->

<% end %>

<% if @match.status == MatchesHelper::STATUS_VOTER_DECLINED %>

	<div id="fade" class="green-overlay"></div><!--.green_overlay-->
	<div id="decline_message" class="light lightbox">
		<div class="close-icon"></div>
		<h2><%= t('voter_dashboard.declined.title')%></h2>
		<div class="pink-hr"></div>
		<div>
			<p><%= t('voter_dashboard.declined.prompt')%></p>
		</div>

	</div><!--.light#decline_message-->

<% end %>

<% if @match.status == MatchesHelper::STATUS_VOLUNTEER_DECLINED %>

	<div id="fade" class="green-overlay"></div><!--.green_overlay-->
	<div id="not_available_message" class="light lightbox">
		<div class="close-icon"></div>
		<h2><%= t('voter_dashboard.canceled.title')%></h2>
		<div class="pink-hr"></div>
		
		<div>
			<p><%= t('voter_dashboard.canceled.prompt')%></p>
		</div>

	</div><!--#not-available.light-->

<% end %>

<div id="fade" class="hide green-overlay"></div><!--.green_overlay-->

<div id="request_time" class="light lightbox hide">

	<div class="close-icon"></div>
	<h2><%= t('voter_dashboard.reschedule.title')%> </h2>
	<div class="pink-hr"></div>
	<div>
	
		<%= form_for :match, url: @match.voter_request_time_url, method: 'POST' do |f| %>
			<h2><%=t('voter_dashboard.matched.reschedule_button')%></h2>
			<textarea name="message" placeholder="<%= t('voter_dashboard.reschedule.prompt')%>"></textarea>
			<%= f.submit t('voter_dashboard.reschedule.button'), class: "button request" %>
		<% end %>
		
	</div>

</div><!--.light#request_time-->

app/views/voters/voter_welcome.html.erb
<main class="dashboard">

	<div class="wrapper">

		<div class="notice"><%= notice %></div>
		<div class="alert"><%= alert %></div>

		<section class="message">

			<div class="wrapper">
				<h1><%= t('voter_dashboard.request.title')%></h1>
			</div>

		</section><!--.message-->

		<section class="next-steps">

			<div class="wrapper">
				<h2><%= t('voter_dashboard.request.steps_title')%></h2>
				<ul>
					<li><%= t('voter_dashboard.request.step1')%></li>
					<li><%= t('voter_dashboard.request.step2')%></li>
					<li><%= t('voter_dashboard.request.step3')%></li>
					<li><%= t('voter_dashboard.request.step4')%></li>
				</ul>

				<div class="view-profile">

					<p><%= t('voter_dashboard.request.profile_link')%></p>
					<input type="text" value="http://votervox.org<%= @voter.home_url%>">
					<p>(You will also find this link in your confirmation email).</p>
				</div><!-- .view-profile -->

			</div><!--.wrapper-->

		</section><!--.more-info-->

		<section class="cancel-request">

			<div class="wrapper">
				<%= link_to t('voter_dashboard.request.cancel'), cancel_voter_path(@voter), class: "btn-outline" %>
				<div class="clear-fix"></div>

			</div><!--.wrapper-->
			
		</section><!--.cancel-request-->

	</div><!--.wrapper-->

</main><!--.dashboard-->

<section class="voter-resources">
			<div class="wrapper">
				<h2><%= t('voter_dashboard.request.resource_title') %></h2>
				<a href="<%= documents_path %>" class="button"><%= t('voter_dashboard.request.button')%></a>
			</div><!--.wrapper-->
			
		</section><!--.voter-resources-->