config/routes.rb
Rails.application.routes.draw do

  # Volunteer routes
  devise_for :volunteers, :path => 'volunteer', :controllers => {:registrations => "registrations"}
  resources :volunteers, :only => [:index] do
    member do
      patch 'approve'
      patch 'ban'
      patch 'make_admin'
    end
  end
  get '/volunteers/home', to: 'volunteers#home', as: 'volunteers_home'

  # Organization routes
  resources :organizations, only: [:index, :new, :create, :destroy]

  # Voter routes
  resources :voters, only: [:index, :new, :create] do
    member do
      get 'cancel'
      get 'activate'
    end
  end
  get '/voters/:hashed_id', to: 'voters#voter_home', as: 'voter_home'

  # Match routes
  resources :matches, only: [:index, :create, :show] do
    member do
      # Volunteer match routes
      post 'message'
      get 'decline'
      post 'complete'
      # Voter match routes
      get 'voter_accept'
      get 'voter_reject'
      post 'voter_request_time'
    end
  end

  # Document routes
  resources :documents, :path => 'voter-resources', only: [:index, :show, :new, :create, :update, :destroy]

  # Metrics routes
  resources :metrics, only: [:index]

  # Translation routes
  resources :locales do
    resources :translations, constraints: { :id => /[^\/]+/ }
  end

  # Application routes
  get '/', to: 'application#index', as: 'homepage'
  get '/feedback', to: 'application#feedback', as: 'feedback'
  post '/submit_feedback', to: 'application#submit_feedback', as: 'submit_feedback'
  get '/absentee-registration', to: 'application#absentee_registration', as: 'absentee_registration'
  get '/about', to: 'application#about', as: 'about'
  get '/guidelines', to: 'application#community_guidelines', as: 'community_guidelines'
  get '/privacy', to: 'application#privacy_policy', as: 'privacy_policy'
  get '/terms', to: 'application#terms_of_service', as: 'terms_of_service'

  root :to => 'application#index'
  
end

app/models/match.rb
class Match < ActiveRecord::Base
	scope :active, -> { where("status in (0,1)") }
	scope :declined, -> { where("status in (2,3)") }
	scope :proposed, -> { where("status = 0") }
	scope :accepted, -> { where("status = 1") }
	scope :volunteer_declined, -> { where("status = 2") }
	scope :voter_declined, -> { where("status = 3") }
	scope :completed, -> { where("status = 4") }

	belongs_to :voter
	belongs_to :volunteer
	has_many :interactions

	# Accessor functions
	def voter_url method
		['/matches/', self.id, '/', method].join('')
	end
	def voter_accept_url
		voter_url 'voter_accept'
	end
	def voter_reject_url
		voter_url 'voter_reject'
	end
	def voter_request_time_url
		voter_url 'voter_request_time'
	end
	def languages
		volunteer.languages & voter.languages
	end

	# Helper functions
	def active?
		status == 0 || status == 1
	end
	def proposed?
		status == 0
	end
	def accepted?
		status == 1
	end
	def completed?
		status == 4
	end
	def matches_volunteer? volunteer_id
		self.volunteer_id == volunteer_id
	end
	def matches_voter? voter_id
		self.voter_id == voter_id
	end

	# Status update functions
	def accept!
		self.status = 1
	end
	def volunteer_decline!
		self.status = 2
	end
	def voter_decline!
		self.status = 3
	end
	def complete!
		self.status = 4
	end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
	before_action :authenticate_volunteer!, only: [:index, :create, :message, :decline, :complete, :show]
	before_action :authenticate_voter!, only: [:voter_accept, :voter_reject, :voter_request_time]
	layout "volunteer"

	### VOLUNTEER ROUTES
	def index
		@volunteer = current_record
		@requests = current_record.match_requests
		@accepted = current_record.matches.active
		@completed = current_record.matches.completed
	end

	def create
		@match = Match.new(match_params)
		if @match.save
			if @match.active?
				redirect_to @match
			else
				redirect_to matches_path
			end
		else
			flash[:notice] = 'Unable to accept match with voter.'
			redirect_to matches_path
		end
	end

	def message
		@match = Match.find params[:id]
		redirect_to :volunteers_home and return if !check_volunteer_match

		Interaction.create_proposal(:match_id => @match.id, :message => params[:message])
		sms_message = [
			t('voter_dashboard.matched.message.sms1'),
			@match.volunteer.firstname,
			t('voter_dashboard.matched.message.sms2'),
			full_url(@match.voter.home_url)
		].join(' ')

		VoterVoxSms.new.send @match.voter.contact, sms_message if @match.voter.sms_contact?
		VoterNotifier.match_made(@match).deliver_now if @match.voter.email_contact?
		
		redirect_to @match
	end

	def decline
		@match = Match.find params[:id]
		redirect_to :volunteers_home and return if !check_volunteer_match

		sms_message = t('voter_dashboard.canceled.message.sms')
		VoterVoxSms.new.send @match.voter.contact, sms_message if @match.voter.sms_contact?
		VoterNotifier.match_declined(@match).deliver_now if @match.voter.email_contact?
		@match.volunteer_decline!
		@match.save
		redirect_to matches_path
	end

	def complete
		@match = Match.find params[:id]
		redirect_to :volunteers_home and return if !check_volunteer_match

		Interaction.create_assistance(match_completion_params)

		sms_message = [t('voter_dashboard.completed.message.sms'), full_url(@match.voter.home_url)].join(' ')
		VoterVoxSms.new.send @match.voter.contact, sms_message if @match.voter.sms_contact?
		VoterNotifier.match_completed(@match).deliver_now if @match.voter.email_contact?
		@match.voter.update(:active => false)
		@match.complete!
		@match.save
		redirect_to matches_path
	end

	def show
		@match = Match.find params[:id]
		redirect_to :volunteers_home if !check_volunteer_match
		
		@proposal = @match.interactions.proposals.first
		@reschedule = @match.interactions.reschedules.first
		@voter = @match.voter
	end


	### VOTER ROUTES
	def voter_accept
		@match = Match.find params[:id]
		redirect_to :new_voter and return if !check_voter_match

		sms_message = t('volunteer_sms.match_accepted', locale: 'en', name: @match.voter.firstname, contact: @match.voter.contact)
		VoterVoxSms.new.send @match.volunteer.phone, sms_message
		VolunteerNotifier.match_accepted(@match).deliver_now
		@match.accept!
		@match.save
		redirect_to @voter.home_url
	end

	def voter_reject
		@match = Match.find params[:id]
		redirect_to :new_voter and return if !check_voter_match

		sms_message = t('volunteer_sms.match_rejected', locale: 'en', name: @match.voter.firstname, url: full_url(matches_path))
		VoterVoxSms.new.send @match.volunteer.phone, sms_message
		VolunteerNotifier.match_rejected(@match).deliver_now
		@match.voter_decline!
		@match.save
		redirect_to @voter.home_url
	end

	def voter_request_time
		@match = Match.find params[:id]
		redirect_to :new_voter and return if !check_voter_match

		Interaction.create_reschedule(:match_id => @match.id, :message => params[:message])

		sms_message = t('volunteer_sms.match_time_change', locale: 'en', name: @match.voter.firstname, url: full_url(match_path(@match)))
		VoterVoxSms.new.send @match.volunteer.phone, sms_message
		VolunteerNotifier.match_time_change(@match).deliver_now
		@match.accept!
		@match.save
		redirect_to @voter.home_url
	end


	private

	def match_params
		params.require(:match).permit(:voter_id, :status).merge(:volunteer_id => current_volunteer.id)
	end
	def match_completion_params
		duration_data = params[:duration].split(':')
		duration = 60 * duration_data[0].to_i + duration_data[1].to_i rescue nil
		{
			:match_id => params[:id],
			:duration => duration,
			:message => params[:message]
		}
	end


	protected

	def check_volunteer_match
		@match.matches_volunteer? current_volunteer.id
	end

	def check_voter_match
		@match.matches_voter? @voter.id
	end

end

app/helpers/matches_helper.rb
module MatchesHelper
	STATUS_PROPOSED = 0
	STATUS_ACCEPTED = 1
	STATUS_VOLUNTEER_DECLINED = 2
	STATUS_VOTER_DECLINED = 3
	STATUS_COMPLETED = 4
end

app/views/matches/index.html.erb
<main class="dashboard">
	<div class="wrapper">
		<section class="stats">
			<div class="stat-info">
				<div class="number"><%= @requests.count %></div>
				<div class="metric">match requests</div>
				<div class="clear-fix"></div>
			</div><!--.stat-info-->
			<div class="stat-info">
				<div class="number"><%= @accepted.count %></div>
				<div class="metric">accepted matches</div>
				<div class="clear-fix"></div>
			</div><!--.stat-info-->
			<div class="stat-info">
				<div class="number"><%= @volunteer.documents.count %></div>
				<div class="metric">documents translated</div>
				<div class="clear-fix"></div>
			</div><!--.stat-info-->
			<div class="stat-info">
				<div class="number"><%= @completed.count %></div>
				<div class="metric">matches completed</div>
				<div class="clear-fix"></div>
			</div><!--.stat-info-->
			<div class="clear-fix"></div>
		</section><!--.stats-->

		<section class="match-results">
			<div class="wrapper">
				<h1>Your Matches</h1>
				<ul class="status">
					<li><a class="matches-toggle current" href="#" data-matches="requested">Your Matches</a></li>
					<li><a class="matches-toggle" href="#" data-matches="accepted">Accepted Matches</a></li>
					<li><a class="matches-toggle" href="#" data-matches="completed">Completed Matches</a></li>
					<div class="clear-fix"></div>
				</ul>

				<div id="requested" class="voter-boxes">
					<% @requests.each do |voter| %>

					<div class="voter-box">
						<div class="voter-info">
							<h2><%= voter.firstname %> <%= voter.lastname %></h2>
							<hr/>
							<ul>
								<li><strong>City:</strong> <%= voter.city %></li>
								<% distance = @volunteer.voter_distance(voter) %>
								<% unless distance.nil? || distance.nan? %>
								<li><strong>Proximity to You:</strong> <%= distance %></li>
								<% end %>
								<li><strong>Requested Language(s):</strong> <%= voter.languages.join(', ') %></li>
								<li><strong>English Proficiency:</strong> <%= voter.english_comfort %></li>
								<% first_time_voter = voter.first_time_voter %>
								<% if first_time_voter %>
								<li><strong>First Time Voter</strong></li>
								<% end %>
							</ul>
						</div><!--.voter-info-->
						<div class="actions">
							<% if @volunteer.approved? %>

							<%= form_for :match, url: matches_path, method: 'POST' do |f| %>
								<%= f.hidden_field :voter_id, :value => voter.id %>
								<%= f.submit 'Accept', class: "button accept" %>
							<% end %>

							<%= form_for :match, url: matches_path, method: 'POST' do |f| %>
								<%= f.hidden_field :voter_id, :value => voter.id %>
								<%= f.hidden_field :status, :value => MatchesHelper::STATUS_VOLUNTEER_DECLINED %>
								<%= f.submit 'Decline', class: "btn-outline decline" %>
							<% end %>

							<% else %>
							<p><em>Your approval is in process. Please check back to accept matches!</em></p>
							<% end %>
						</div><!--.actions-->
					</div><!--.voter-box-->
					<% end %>

					<% if @requests.length == 0 %>
					<div class="voter-box">
						<h2 class="no-matches">You have no current requested matches</h2>
					</div>
					<% end %>
				</div><!--#requested.voter-boxes-->

				<div id="accepted" class="hide voter-boxes">

					<% @accepted.each do |match| %>
					<div class="voter-box">
						<div class="voter-info">
							<h2><%= match.voter.firstname %> <%= match.voter.lastname %></h2>
							<hr/> 

							<span class="accepted-tag">Accepted</span>
							<ul>
								<li><strong>City:</strong> <%= match.voter.city %></li>
								<% distance = @volunteer.voter_distance(match.voter) %>
								<% unless distance.nil? || distance.nan? %>
								<li><strong>Proximity to You:</strong> <%= distance %></li>
								<% end %>
								<li><strong>Requested Language:</strong> <%= match.voter.languages.join(', ') %></li>
								<li><strong>English Proficiency:</strong> <%= match.voter.english_comfort %></li>
								<% first_time_voter = match.voter.first_time_voter %>
								<% if first_time_voter %>
									<li><strong>First Time Voter</strong></li>
								<% end %>
							</ul>
						</div><!--.voter-info-->
						<div class="actions">
							<%= link_to 'View Match', match_path(match), class: "button accept" %>
							<%= link_to 'Decline', decline_match_path(match), method: :get, data: { confirm: 'Are you sure you want to decline this match?' }, class: "btn-outline decline" %>
						</div><!--.actions-->
					</div><!--.voter-box-->
					<% end %>
					<% if @accepted.length == 0 %>
					<div class="voter-box">
									<h2 class="no-matches">You currently have no accepted matches</h2>
					</div>
					<% end %>
				</div><!--#accepted.voter-boxes-->

				<div id="completed" class="hide voter-boxes">
					<% @completed.each do |match| %>
					<div class="voter-box">
						<div class="voter-info">
							<h2><%= match.voter.firstname %> <%= match.voter.lastname %> <span class="completed-tag desktop">Completed</span></h2>
							<hr/>
							<span class="completed-tag mobile-only">Completed</span> 
							<ul>
								<li><strong>City:</strong> <%= match.voter.city %></li>
								<% distance = @volunteer.voter_distance(match.voter) %>
								<% unless distance.nil? || distance.nan? %>
								<li><strong>Proximity to You:</strong> <%= distance %></li>
								<% end %>
								<li><strong>Requested Language:</strong> <%= match.voter.languages.join(', ') %></li>
								<li><strong>English Proficiency:</strong> <%= match.voter.english_comfort %></li>
								<% first_time_voter = match.voter.first_time_voter %>
								<% if first_time_voter %>
									<li><strong>First Time Voter</strong></li>
								<% end %>
							</ul>
						</div><!--.voter-info-->
						
					</div><!--.voter-box-->
					<% end %>
					<% if @completed.length == 0 %>
					<div class="voter-box">
						<h2 class="no-matches">You currently have no completed matches</h2>
					</div>
					<% end %>
				</div><!--#completed.voter-boxes-->

				<div class="clear-fix"></div>

			</div><!--.wrapper-->

		</section><!--.match-results-->

	</div><!--.wrapper-->
</main>

app/views/matches/show.html.erb
<main class="dashboard match-contact">
		<div class="wrapper">
			
			<section class="match-results">
				<div class="wrapper">
					<h1>Your Voter Match</h1>

					<div class="voter-box">
						<div class="top-container">
							<div class="voter-info">
								<h2><%= @voter.firstname %> <%= @voter.lastname %>
									<hr/>
								<span class="desktop accepted-tag">Accepted</span></h2>
								<% if @match.accepted? %>
									<span class="accepted-tag mobile-only">Accepted</span>
								<% end %>
								<ul>
									<li><strong>City:</strong> <%= @voter.city %></li>
									<% distance = @voter.volunteer_distance(@volunteer) %>

									<% unless distance.nil? || distance.nan? %>
									<li><strong>Proximity to You:</strong> <%= distance %></li>
									<% end %>

									<li><strong>Requested Language:</strong> <%= @voter.languages.join(', ') %></li>
									<li><strong>English Proficiency:</strong> <%= @voter.english_comfort %></li>
									<% first_time_voter = @voter.first_time_voter %>
									<% if first_time_voter %>
										<li><strong>First Time Voter</strong></li>
									<% end %>
								</ul>
							</div><!--.voter-info-->
							<div class="clear-fix"></div>
						</div>
					
					<div class="contact-box">
						<div class="wrapper">
							<% if @match.accepted? %>

								<% if @reschedule.present? %>
									<h2><%= @voter.firstname %> has requested a new time:</h2>
									<div class="pink-box">
									<p><em><%= @reschedule.message %></em></p>
									</div><!--.pink-box-->
								<% else %>
									<h2><%= @voter.firstname %> has accepted your suggested time:</h2>
								<% end %>
								<hr/>
								<h2>The next step:</h2>
								<p class="next-contact">Contact <%= @voter.firstname %> to confirm specific time and location.</p>
								<div class="black-box contact-info">
									<p><%= @voter.firstname %>'s Contact Information:</p>
									<div class="phone-number"><%= @voter.contact %></div>
								</div>
							<% end %>

							<% if @proposal.nil? %>

								<%= form_for :match, url: message_match_path(@match), method: 'POST' do |f| %>
									<h2>Contact <%= @voter.firstname %></h2>
									<textarea name="message"></textarea>
									<%= f.submit 'Send Your Message', class: "button" %>
								<% end %>

							<% else %>
							<div class="original-message">
								<p>Your original message:</p>
								<div class="grey-box">
									<p><em><%= @proposal.message %></em></p>
								</div><!--.grey-box-->
							</div>
							<% end %>
						</div><!--.wrapper-->
					</div><!--.contact-box-->
					<div class="actions">
						<% if @match.accepted? %>
							<%= link_to "Match Completed", "#", { :class => "lightbox-button button accept", :"data-lightbox" => "accepted"} %>
						<% end %>

						<%= link_to 'Decline', decline_match_path(@match), method: :get, data: { confirm: 'Are you sure you want to decline this match?' }, class: "btn-outline decline" %>

					</div><!--.actions-->
				</div><!--.voter-box-->
			</div><!--.wrapper-->
				
		</section><!--.match-results-->

	</div><!--.wrapper-->
</main>


<% if @match.accepted? %>
	<div id="accepted" class="lightbox light hide">
		<div class="close-icon"></div>
		<h2>Thank you for helping out <%= @voter.firstname %>!</h2>
		
		<p>Please take a few seconds to answer some questions.</p>
		<div class="pink-hr"></div>
		
		<%= form_for :match, url: complete_match_path(@match), method: 'POST' do |f| %>
			<label for="time_spent">How much time did you spend helping <%= @voter.firstname %>?</label>
			<input id="time_spent" type="text" name="duration" placeholder="HH:MM" value="" />
			<label for="feedback">What was your experience like? Do you have feedback or suggestions?</label>
			<textarea id="feedback" name="message" placeholder="Feedback on experience"></textarea>
			<%= f.submit 'Submit', class: "button" %>
		<% end %>
			
		</div><!--.request-->

	</div><!--.white_content-->
	<div id="fade" class="green-overlay hide"></div><!--.green_overlay-->

<% end %>